[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
aptPackages = ["ta-lib-dev", "build-essential"]

[phases.install]
cmds = ["pip3 install -r requirements.txt"]

[start]
cmd = "python3 backtesting.py -c 500 -t 30"
